"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "seats",
      [
        {
          id: -1,
          vehicle_id: 1,
          unique_code: "A1",
          seat_type: "Window",
          status:"Reserved",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
            id: -2,
            vehicle_id: 1,
            unique_code: "A2",
            seat_type: "Aisle",
            status:"Reserved",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            id: -3,
            vehicle_id: 1,
            unique_code: "A3",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
         },
         {
            id: -4,
            vehicle_id: 1,
            unique_code: "A4",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -5,
            vehicle_id: 1,
            unique_code: "A5",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -6,
            vehicle_id: 1,
            unique_code: "A6",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -7,
            vehicle_id: 1,
            unique_code: "A7",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -8,
            vehicle_id: 1,
            unique_code: "A8",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -9,
            vehicle_id: 1,
            unique_code: "A9",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -10,
            vehicle_id: 1,
            unique_code: "A10",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -11,
            vehicle_id: 1,
            unique_code: "A11",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -12,
            vehicle_id: 1,
            unique_code: "A12",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -13,
            vehicle_id: 1,
            unique_code: "A13",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -14,
            vehicle_id: 1,
            unique_code: "A14",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -15,
            vehicle_id: 1,
            unique_code: "A15",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -16,
            vehicle_id: 1,
            unique_code: "A16",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -17,
            vehicle_id: 1,
            unique_code: "A17",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -18,
            vehicle_id: 1,
            unique_code: "A18",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -19,
            vehicle_id: 1,
            unique_code: "B1",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -20,
            vehicle_id: 1,
            unique_code: "B2",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -21,
            vehicle_id: 1,
            unique_code: "B3",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -22,
            vehicle_id: 1,
            unique_code: "B4",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -23,
            vehicle_id: 1,
            unique_code: "B5",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -24,
            vehicle_id: 1,
            unique_code: "B6",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -25,
            vehicle_id: 1,
            unique_code: "B7",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -26,
            vehicle_id: 1,
            unique_code: "B8",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -27,
            vehicle_id: 1,
            unique_code: "B9",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -28,
            vehicle_id: 1,
            unique_code: "B10",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -29,
            vehicle_id: 1,
            unique_code: "B11",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -30,
            vehicle_id: 1,
            unique_code: "B12",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -31,
            vehicle_id: 1,
            unique_code: "B13",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -32,
            vehicle_id: 1,
            unique_code: "B14",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -33,
            vehicle_id: 1,
            unique_code: "B15",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -34,
            vehicle_id: 1,
            unique_code: "B16",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -35,
            vehicle_id: 1,
            unique_code: "B17",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -36,
            vehicle_id: 1,
            unique_code: "B18",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -37,
            vehicle_id: 1,
            unique_code: "C1",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -38,
            vehicle_id: 1,
            unique_code: "AC2",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -39,
            vehicle_id: 1,
            unique_code: "C3",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -40,
            vehicle_id: 1,
            unique_code: "C4",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -41,
            vehicle_id: 1,
            unique_code: "C5",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -42,
            vehicle_id: 2,
            unique_code: "A1",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -43,
            vehicle_id: 2,
            unique_code: "A2",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -44,
            vehicle_id: 2,
            unique_code: "B1",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -45,
            vehicle_id: 2,
            unique_code: "B2",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -46,
            vehicle_id: 2,
            unique_code: "B3",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -47,
            vehicle_id: 2,
            unique_code: "B4",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -48,
            vehicle_id: 2,
            unique_code: "C1",
            seat_type: "Window",
            status:"Booked",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -49,
            vehicle_id: 2,
            unique_code: "C2",
            seat_type: "Aisle",
            status:"Booked",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -50,
            vehicle_id: 2,
            unique_code: "C3",
            seat_type: "Aisle",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
          {
            id: -51,
            vehicle_id: 2,
            unique_code: "C4",
            seat_type: "Window",
            status:"Available",
            created_at: new Date(),
            updated_at: new Date(),
          },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("seats", null, {});
  },
};
